<?php
  
  require_once('controllers/EnlacesPaginacionControlador.php');
  require_once('models/EnlacesPaginacionModelo.php');
  require_once('controllers/UsuarioControlador.php');
  require_once('models/UsuarioModelo.php');
  require_once('controllers/ConsultorioControlador.php');
  require_once('models/ConsultorioModelo.php');
  require_once('controllers/AnanmesisControlador.php');
  require_once('models/AnanmesisModelo.php');
  require_once('controllers/AgendaControlador.php');
  require_once('models/AgendaModelo.php');
  require_once('controllers/PacienteControlador.php');
  require_once('models/PacienteModelo.php');
  require_once('controllers/EvMedicaControlador.php');
  require_once('models/EvMedicaModelo.php');
  require_once('controllers/RecetarioControlador.php');
  require_once('models/RecetarioModelo.php');
  require_once('controllers/CertificacionControlador.php');
  require_once('models/CertificacionModelo.php');
  require_once('controllers/OrdMedControlador.php');
  require_once('models/OrdMedModelo.php');
  require_once('controllers/RemisionControlador.php');
  require_once('models/RemisionModelo.php');
  require_once('controllers/ConsInfControlador.php');
  require_once('models/ConsInfModelo.php');
  require_once('controllers/TarifaControlador.php');
  require_once('models/TarifaModelo.php');
  require_once('controllers/FacturaControlador.php');
  require_once('models/FacturaModelo.php');
  require_once('controllers/MunicipioControlador.php');
  require_once('models/MunicipioModelo.php');
  require_once('controllers/DepartamentoControlador.php');
  require_once('models/DepartamentoModelo.php');
  require_once('controllers/Cie10Controlador.php');
  require_once('models/Cie10Modelo.php');
  require_once('controllers/CupsControlador.php');
  require_once('models/CupsModelo.php');
  require_once('controllers/ConsultaControlador.php');
  require_once('models/ConsultaModelo.php');
  require_once('controllers/ModeloRecetarioControlador.php');
  require_once('models/ModeloRecetarioModelo.php');
  require_once('controllers/ModeloConsentimientoControlador.php');
  require_once('models/ModeloConsentimientoModelo.php');
  require_once('controllers/DetalleFacturaControlador.php');
  require_once('models/DetalleFacturaModelo.php');
  require_once('controllers/TipoDocumentoControlador.php');
  require_once('models/TipoDocumentoModelo.php');
  require_once('controllers/DetalleFacturaPControlador.php');
  require_once('models/DetalleFacturaPModelo.php');
  require_once('controllers/HoraControlador.php');
  require_once('models/HoraModelo.php');
  require_once('controllers/AgendaPControlador.php');
  require_once('models/AgendaPModelo.php');

  $obj = new EnlacesPaginacionControlador();
  $obj->mostrarPagina();

?>